[package]
name = "ktls-sys"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/ktls-sys"
documentation = "https://docs.rs/ktls-sys"
readme = "README.md"
description = """
FFI bindings for `linux/tls.h`
"""

[dependencies]
