[package]
name = "ktls"
version = "4.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hapsoc/ktls"
documentation = "https://docs.rs/ktls"
readme = "README.md"
description = """
Configures kTLS for tokio-rustls client and server connections.
"""

[dependencies]
libc = { version = "0.2.148", features = ["const-extern-fn"] }
thiserror = "1.0.49"
tracing = "0.1.37"
tokio-rustls = "0.24.1"
rustls = { version = "0.21.7", features = ["secret_extraction"] }
smallvec = "1.11.1"
memoffset = "0.9.0"
pin-project-lite = "0.2.13"
tokio = { version = "1.32.0", features = ["net", "macros", "io-util"] }
futures = "0.3.28"
ktls-sys = "1.0.0"
ktls-recvmsg = { version = "0.1.3" }
num_enum = "0.7.0"

[dev-dependencies]
lazy_static = "1.4.0"
oorandom = "11.1.3"
rcgen = "0.11.3"
socket2 = "0.5.4"
tokio = { version = "1.32.0", features = ["full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
